server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

logging:
  level:
    root: info
    org.springframework.web: debug
    feichai.mybatis: debug
  file:
    path: logs
  pattern:
    console: "%d{HH:mm:ss} %clr(%-5level) %logger{36} - %clr(%msg%n)"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/voteman?characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 数据库访问配置, 使用druid数据源
      db-type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/voteman?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 12345678
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如 x.y.z.service.*,配置多个英文逗号分隔
#      aop-patterns: org.feichai.*.service.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        # 最大空闲连接数
        max-idle: 500
        # 最大连接数（负数代表无限制）
        max-active: 2000
        # 最大阻塞等待时长
        max-wait: 10000
    # 连接超时时间
    timeout: 0

  cache:
    type: redis

mybatis:
  type-aliases-package: org.feichai.voteman.domain,org.feichai.system.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    # 打印所有sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: org.feichai.common.util.enums
mapper:
  mappers: org.feichai.common.config.MyMapper
  not-empty: false
  identity: MYSQL

feichai:
  showsql: true
  timeFormat: yyyy-MM-dd HH:mm:ss
  openAopLog: true
  shiro:
    expireIn: 1800
    sessionTimeout: 1800000
    cookieTimeout: 86400
    # 免认证路径配置
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/druid/**,/test/**,/user/regist,/gifCode,/,/actuator/**,/test/**
    loginurl: /login
    logoutUrl: /logout
    unauthorizedUrl: /403
  validateCode:
    width: 146
    height: 33
    length: 4

#imagePath:
imagePath: /Users/gaomugong/IdeaProjects/java-playground/springboot/voteman/media/images/

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql