server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  security:
    user:
      name: admin
      password: admin
      roles: manager
  devtools:
    restart:
      exclude: static/**,public/**

logging:
  level:
    root: info
    org.springframework.web: debug
    org.feichai.themyleaf.controller: trace
  file:
    path: logs
  pattern:
    console: "%d{HH:mm:ss} %clr(%-5level) %logger{36} - %clr(%msg%n)"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
